### ISSUE TITLE
Python error on krita flatpak(linux)

### ISSUE THREAD

**Issue by starget24** [EyeOdin/imagine_board#1]
After enabling the plugin and restarting krita on the flatpak version (linux) this will appear:

![image](https://user-images.githubusercontent.com/92924912/210272506-077f45d1-5860-4e25-bb5a-108e1070eb04.png)

Full log:

```
TypeError
Python 3.10.6: /usr/bin/python3
Mon Jan  2 14:08:54 2023

A problem occurred in a Python script.  Here is the sequence of
function calls leading up to the error, in the order they occurred.

 /app/lib/krita-python-libs/krita/dockwidgetfactory.py in createDockWidget(self=<krita.dockwidgetfactory.DockWidgetFactory object>)
   14         super(DockWidgetFactory, self).__init__(_id, _dockPosition)
   15         self.klass = _klass
   16 
   17     def createDockWidget(self):
   18         return self.klass()
self = <krita.dockwidgetfactory.DockWidgetFactory object>
self.klass = <class 'imagine_board.imagine_board_docker.ImagineBoard_Docker'>

 /home/Pacn/.var/app/org.kde.krita/data/krita/pykrita/imagine_board/imagine_board_docker.py in __init__(self=<imagine_board.imagine_board_docker.ImagineBoard_Docker object>)
  154         self.Timer()
  155         self.Extension()
  156         self.Settings()
  157 
  158     def Variables(self):
self = <imagine_board.imagine_board_docker.ImagineBoard_Docker object>
self.Settings = <bound method ImagineBoard_Docker.Settings of <i...imagine_board_docker.ImagineBoard_Docker object>>

 /home/Pacn/.var/app/org.kde.krita/data/krita/pykrita/imagine_board/imagine_board_docker.py in Settings(self=<imagine_board.imagine_board_docker.ImagineBoard_Docker object>)
  579             Krita.instance().writeSetting("Imagine Board", "slideshow_time", str(1000) )
  580         else:
  581             tempo = QTime(0,0,0).addMSecs(float(ms))
  582             self.dialog.menu_slideshow_time.setTime(tempo)
  583 
tempo undefined
global QTime = <class 'PyQt5.QtCore.QTime'>
).addMSecs = <built-in function addMSecs>
builtinfloat = <class 'float'>
ms = '1000'
TypeError: addMSecs(self, ms: int): argument 1 has unexpected type 'float'
    __cause__ = None
    __class__ = <class 'TypeError'>
    __context__ = None
    __delattr__ = <method-wrapper '__delattr__' of TypeError object>
    __dict__ = {}
    __dir__ = <built-in method __dir__ of TypeError object>
    __doc__ = 'Inappropriate argument type.'
    __eq__ = <method-wrapper '__eq__' of TypeError object>
    __format__ = <built-in method __format__ of TypeError object>
    __ge__ = <method-wrapper '__ge__' of TypeError object>
    __getattribute__ = <method-wrapper '__getattribute__' of TypeError object>
    __gt__ = <method-wrapper '__gt__' of TypeError object>
    __hash__ = <method-wrapper '__hash__' of TypeError object>
    __init__ = <method-wrapper '__init__' of TypeError object>
    __init_subclass__ = <built-in method __init_subclass__ of type object>
    __le__ = <method-wrapper '__le__' of TypeError object>
    __lt__ = <method-wrapper '__lt__' of TypeError object>
    __ne__ = <method-wrapper '__ne__' of TypeError object>
    __new__ = <built-in method __new__ of type object>
    __reduce__ = <built-in method __reduce__ of TypeError object>
    __reduce_ex__ = <built-in method __reduce_ex__ of TypeError object>
    __repr__ = <method-wrapper '__repr__' of TypeError object>
    __setattr__ = <method-wrapper '__setattr__' of TypeError object>
    __setstate__ = <built-in method __setstate__ of TypeError object>
    __sizeof__ = <built-in method __sizeof__ of TypeError object>
    __str__ = <method-wrapper '__str__' of TypeError object>
    __subclasshook__ = <built-in method __subclasshook__ of type object>
    __suppress_context__ = False
    __traceback__ = <traceback object>
    args = ("addMSecs(self, ms: int): argument 1 has unexpected type 'float'",)
    with_traceback = <built-in method with_traceback of TypeError object>

The above is a description of an error in a Python program.  Here is
the original traceback:

Traceback (most recent call last):
  File "/app/lib/krita-python-libs/krita/dockwidgetfactory.py", line 18, in createDockWidget
    return self.klass()
  File "/home/Pacn/.var/app/org.kde.krita/data/krita/pykrita/imagine_board/imagine_board_docker.py", line 156, in __init__
    self.Settings()
  File "/home/Pacn/.var/app/org.kde.krita/data/krita/pykrita/imagine_board/imagine_board_docker.py", line 581, in Settings
    tempo = QTime(0,0,0).addMSecs(float(ms))
TypeError: addMSecs(self, ms: int): argument 1 has unexpected type 'float'
```

Ignoring it makes krita function normally but the plugin is nowhere to be seen.

**Comment by EyeOdin** [comment]
On windows it works either way, regardless I just updated it now.
Check if that error is still there or not but I think it it is solved as it is neutral for me.

**Comment by starget24** [comment]
Just downloaded the updated version and this is what shows at launch 

![image](https://user-images.githubusercontent.com/92924912/210783287-1fe09dbb-cb0f-4b73-ace6-55257268809e.png)

Full log:
```

TypeError
Python 3.10.6: /usr/bin/python3
Thu Jan  5 07:44:15 2023

A problem occurred in a Python script.  Here is the sequence of
function calls leading up to the error, in the order they occurred.

 /home/Pacn/.var/app/org.kde.krita/data/krita/pykrita/imagine_board/imagine_board_modulo.py in paintEvent(self=<imagine_board.imagine_board_modulo.ImagineBoard_Preview object>, event=<PyQt5.QtGui.QPaintEvent object>)
 1069         # Display Pixmap
 1070         if (self.is_null == True or (self.qpixmap.isNull() == True and self.is_animation == False and self.drop == False)):
 1071             self.Image_Default(painter)
 1072         else:
 1073             self.Image_Calculations()
self = <imagine_board.imagine_board_modulo.ImagineBoard_Preview object>
self.Image_Default = <bound method ImagineBoard_Preview.Image_Default...magine_board_modulo.ImagineBoard_Preview object>>
painter = <PyQt5.QtGui.QPainter object>

 /home/Pacn/.var/app/org.kde.krita/data/krita/pykrita/imagine_board/imagine_board_modulo.py in Image_Default(self=<imagine_board.imagine_board_modulo.ImagineBoard_Preview object>, painter=<PyQt5.QtGui.QPainter object>)
 1212         w2 = self.widget_width * 0.5
 1213         h2 = self.widget_height * 0.5
 1214         painter.drawEllipse(w2 - (0.2*side), h2 - (0.2*side), 0.4*side, 0.4*side)
 1215 
 1216 class ImagineBoard_Grid(QWidget):
painter = <PyQt5.QtGui.QPainter object>
painter.drawEllipse = <built-in method drawEllipse of QPainter object>
w2 = 130.0
side = 194
h2 = 97.0
TypeError: arguments did not match any overloaded call:
  drawEllipse(self, r: QRectF): argument 1 has unexpected type 'float'
  drawEllipse(self, r: QRect): argument 1 has unexpected type 'float'
  drawEllipse(self, x: int, y: int, w: int, h: int): argument 1 has unexpected type 'float'
  drawEllipse(self, center: Union[QPointF, QPoint], rx: float, ry: float): argument 1 has unexpected type 'float'
  drawEllipse(self, center: QPoint, rx: int, ry: int): argument 1 has unexpected type 'float'
    __cause__ = None
    __class__ = <class 'TypeError'>
    __context__ = None
    __delattr__ = <method-wrapper '__delattr__' of TypeError object>
    __dict__ = {}
    __dir__ = <built-in method __dir__ of TypeError object>
    __doc__ = 'Inappropriate argument type.'
    __eq__ = <method-wrapper '__eq__' of TypeError object>
    __format__ = <built-in method __format__ of TypeError object>
    __ge__ = <method-wrapper '__ge__' of TypeError object>
    __getattribute__ = <method-wrapper '__getattribute__' of TypeError object>
    __gt__ = <method-wrapper '__gt__' of TypeError object>
    __hash__ = <method-wrapper '__hash__' of TypeError object>
    __init__ = <method-wrapper '__init__' of TypeError object>
    __init_subclass__ = <built-in method __init_subclass__ of type object>
    __le__ = <method-wrapper '__le__' of TypeError object>
    __lt__ = <method-wrapper '__lt__' of TypeError object>
    __ne__ = <method-wrapper '__ne__' of TypeError object>
    __new__ = <built-in method __new__ of type object>
    __reduce__ = <built-in method __reduce__ of TypeError object>
    __reduce_ex__ = <built-in method __reduce_ex__ of TypeError object>
    __repr__ = <method-wrapper '__repr__' of TypeError object>
    __setattr__ = <method-wrapper '__setattr__' of TypeError object>
    __setstate__ = <built-in method __setstate__ of TypeError object>
    __sizeof__ = <built-in method __sizeof__ of TypeError object>
    __str__ = <method-wrapper '__str__' of TypeError object>
    __subclasshook__ = <built-in method __subclasshook__ of type object>
    __suppress_context__ = False
    __traceback__ = <traceback object>
    args = ("arguments did not match any overloaded call:\n  d... ry: int): argument 1 has unexpected type 'float'",)
    with_traceback = <built-in method with_traceback of TypeError object>

The above is a description of an error in a Python program.  Here is
the original traceback:

Traceback (most recent call last):
  File "/home/Pacn/.var/app/org.kde.krita/data/krita/pykrita/imagine_board/imagine_board_modulo.py", line 1071, in paintEvent
    self.Image_Default(painter)
  File "/home/Pacn/.var/app/org.kde.krita/data/krita/pykrita/imagine_board/imagine_board_modulo.py", line 1214, in Image_Default
    painter.drawEllipse(w2 - (0.2*side), h2 - (0.2*side), 0.4*side, 0.4*side)
TypeError: arguments did not match any overloaded call:
  drawEllipse(self, r: QRectF): argument 1 has unexpected type 'float'
  drawEllipse(self, r: QRect): argument 1 has unexpected type 'float'
  drawEllipse(self, x: int, y: int, w: int, h: int): argument 1 has unexpected type 'float'
  drawEllipse(self, center: Union[QPointF, QPoint], rx: float, ry: float): argument 1 has unexpected type 'float'
  drawEllipse(self, center: QPoint, rx: int, ry: int): argument 1 has unexpected type 'float'
```

After that the plugin docker actually shows but its empty 

![image](https://user-images.githubusercontent.com/92924912/210783615-c092f5f9-ae5e-4ef3-9e22-6e8542a70e1c.png)

if i hover the mouse over it, it shows the same error that at launch.

**Comment by EyeOdin** [comment]
so 1 and 1.0 is a difference to big to handle for your Linux.... what are you on Arch Linux? or another?

**Comment by EyeOdin** [comment]
I made a QRectF for all Ellipses.

**Comment by starget24** [comment]
> so 1 and 1.0 is a difference to big to handle for your Linux.... what are you on Arch Linux? or another?

I am on fedora 37 but in my case it really doesn't matter since i am using a flatpak (binaries from the krita team bundle in a container) every version of krita and its dependencies are the same no matter the distro or linux version, for development its good cause everyone uses the same python version the same krita version,etc. 

-----------------------------------------------------------------------------------------------

Ok so, now when i launch krita everything loads normally but after a couple of seconds i get the following: 
![image](https://user-images.githubusercontent.com/92924912/210926748-5aeb8e91-277f-4499-9fab-639476f628d5.png)

Log: 
```
TypeError
Python 3.10.6: /usr/bin/python3
Thu Jan  5 22:53:09 2023

A problem occurred in a Python script.  Here is the sequence of
function calls leading up to the error, in the order they occurred.

 /home/Pacn/.var/app/org.kde.krita/data/krita/pykrita/imagine_board/imagine_board_docker.py in Index_Number(self=<imagine_board.imagine_board_docker.ImagineBoard_Docker object>, value=0.0)
 1953         self.Index_Block(True)
 1954         self.preview_index = int(value-1) # Humans start at 1 and script starts at 0
 1955         self.layout.index_slider.setValue(value)
 1956         if self.images_found == True:
 1957             self.Display_Update()
self = <imagine_board.imagine_board_docker.ImagineBoard_Docker object>
self.layout = <PyQt5.QtWidgets.QWidget object>
self.layout.index_slider = <PyQt5.QtWidgets.QSlider object>
self.layout.index_slider.setValue = <built-in method setValue of QSlider object>
value = 0.0
TypeError: setValue(self, a0: int): argument 1 has unexpected type 'float'
    __cause__ = None
    __class__ = <class 'TypeError'>
    __context__ = None
    __delattr__ = <method-wrapper '__delattr__' of TypeError object>
    __dict__ = {}
    __dir__ = <built-in method __dir__ of TypeError object>
    __doc__ = 'Inappropriate argument type.'
    __eq__ = <method-wrapper '__eq__' of TypeError object>
    __format__ = <built-in method __format__ of TypeError object>
    __ge__ = <method-wrapper '__ge__' of TypeError object>
    __getattribute__ = <method-wrapper '__getattribute__' of TypeError object>
    __gt__ = <method-wrapper '__gt__' of TypeError object>
    __hash__ = <method-wrapper '__hash__' of TypeError object>
    __init__ = <method-wrapper '__init__' of TypeError object>
    __init_subclass__ = <built-in method __init_subclass__ of type object>
    __le__ = <method-wrapper '__le__' of TypeError object>
    __lt__ = <method-wrapper '__lt__' of TypeError object>
    __ne__ = <method-wrapper '__ne__' of TypeError object>
    __new__ = <built-in method __new__ of type object>
    __reduce__ = <built-in method __reduce__ of TypeError object>
    __reduce_ex__ = <built-in method __reduce_ex__ of TypeError object>
    __repr__ = <method-wrapper '__repr__' of TypeError object>
    __setattr__ = <method-wrapper '__setattr__' of TypeError object>
    __setstate__ = <built-in method __setstate__ of TypeError object>
    __sizeof__ = <built-in method __sizeof__ of TypeError object>
    __str__ = <method-wrapper '__str__' of TypeError object>
    __subclasshook__ = <built-in method __subclasshook__ of type object>
    __suppress_context__ = False
    __traceback__ = <traceback object>
    args = ("setValue(self, a0: int): argument 1 has unexpected type 'float'",)
    with_traceback = <built-in method with_traceback of TypeError object>

The above is a description of an error in a Python program.  Here is
the original traceback:

Traceback (most recent call last):
  File "/home/Pacn/.var/app/org.kde.krita/data/krita/pykrita/imagine_board/imagine_board_docker.py", line 1955, in Index_Number
    self.layout.index_slider.setValue(value)
TypeError: setValue(self, a0: int): argument 1 has unexpected type 'float'
```

If i close i can actually see the docker working 
![image](https://user-images.githubusercontent.com/92924912/210923143-43d1faa2-79af-44c8-bfbe-a1577e873850.png)
Both Preview and Grid mode seems to work normally, after clicking settings the following appears:

![image](https://user-images.githubusercontent.com/92924912/210923345-4222d610-ada9-4c6c-8915-fed990b00aaf.png)

Log:
```
TypeError
Python 3.10.6: /usr/bin/python3
Thu Jan  5 22:20:47 2023

A problem occurred in a Python script.  Here is the sequence of
function calls leading up to the error, in the order they occurred.

 /home/Pacn/.var/app/org.kde.krita/data/krita/pykrita/imagine_board/imagine_board_docker.py in Menu_Settings(self=<imagine_board.imagine_board_docker.ImagineBoard_Docker object>)
 1213         height = screen_zero.height()
 1214         size = 500
 1215         self.dialog.setGeometry(width*0.5-size*0.5, height*0.5-size*0.5, size, size)
 1216     def Menu_Manual(self):
 1217         url = "https://github.com/EyeOdin/imagine_board/wiki"
self = <imagine_board.imagine_board_docker.ImagineBoard_Docker object>
self.dialog = <PyQt5.QtWidgets.QDialog object>
self.dialog.setGeometry = <built-in method setGeometry of QDialog object>
width = 1920
size = 500
height = 1080
TypeError: arguments did not match any overloaded call:
  setGeometry(self, a0: QRect): argument 1 has unexpected type 'float'
  setGeometry(self, ax: int, ay: int, aw: int, ah: int): argument 1 has unexpected type 'float'
    __cause__ = None
    __class__ = <class 'TypeError'>
    __context__ = None
    __delattr__ = <method-wrapper '__delattr__' of TypeError object>
    __dict__ = {}
    __dir__ = <built-in method __dir__ of TypeError object>
    __doc__ = 'Inappropriate argument type.'
    __eq__ = <method-wrapper '__eq__' of TypeError object>
    __format__ = <built-in method __format__ of TypeError object>
    __ge__ = <method-wrapper '__ge__' of TypeError object>
    __getattribute__ = <method-wrapper '__getattribute__' of TypeError object>
    __gt__ = <method-wrapper '__gt__' of TypeError object>
    __hash__ = <method-wrapper '__hash__' of TypeError object>
    __init__ = <method-wrapper '__init__' of TypeError object>
    __init_subclass__ = <built-in method __init_subclass__ of type object>
    __le__ = <method-wrapper '__le__' of TypeError object>
    __lt__ = <method-wrapper '__lt__' of TypeError object>
    __ne__ = <method-wrapper '__ne__' of TypeError object>
    __new__ = <built-in method __new__ of type object>
    __reduce__ = <built-in method __reduce__ of TypeError object>
    __reduce_ex__ = <built-in method __reduce_ex__ of TypeError object>
    __repr__ = <method-wrapper '__repr__' of TypeError object>
    __setattr__ = <method-wrapper '__setattr__' of TypeError object>
    __setstate__ = <built-in method __setstate__ of TypeError object>
    __sizeof__ = <built-in method __sizeof__ of TypeError object>
    __str__ = <method-wrapper '__str__' of TypeError object>
    __subclasshook__ = <built-in method __subclasshook__ of type object>
    __suppress_context__ = False
    __traceback__ = <traceback object>
    args = ("arguments did not match any overloaded call:\n  s... ah: int): argument 1 has unexpected type 'float'",)
    with_traceback = <built-in method with_traceback of TypeError object>

The above is a description of an error in a Python program.  Here is
the original traceback:

Traceback (most recent call last):
  File "/home/Pacn/.var/app/org.kde.krita/data/krita/pykrita/imagine_board/imagine_board_docker.py", line 1215, in Menu_Settings
    self.dialog.setGeometry(width*0.5-size*0.5, height*0.5-size*0.5, size, size)
TypeError: arguments did not match any overloaded call:
  setGeometry(self, a0: QRect): argument 1 has unexpected type 'float'
  setGeometry(self, ax: int, ay: int, aw: int, ah: int): argument 1 has unexpected type 'float'
```

After closing the error the settings panel seems to work normally(changing the sync -> items -> list options trigger first error after launching krita).

Going into reference mode gets me:

![image](https://user-images.githubusercontent.com/92924912/210924533-c420cf37-5b53-4927-b907-ee995d547586.png)

Log:
```
TypeError
Python 3.10.6: /usr/bin/python3
Thu Jan  5 22:30:40 2023

A problem occurred in a Python script.  Here is the sequence of
function calls leading up to the error, in the order they occurred.

 /home/Pacn/.var/app/org.kde.krita/data/krita/pykrita/imagine_board/imagine_board_modulo.py in paintEvent(self=<imagine_board.imagine_board_modulo.ImagineBoard_Reference object>, event=<PyQt5.QtGui.QPaintEvent object>)
 3243             h2 = self.widget_height * 0.5
 3244             poly_quad = QPolygon([
 3245                 QPoint(w2 - (0.2*side), h2 - (0.2*side)),
 3246                 QPoint(w2 + (0.2*side), h2 - (0.2*side)),
 3247                 QPoint(w2 + (0.2*side), h2 + (0.2*side)),
global QPoint = <class 'PyQt5.QtCore.QPoint'>
w2 = 130.0
side = 127
h2 = 63.5
TypeError: arguments did not match any overloaded call:
  QPoint(): too many arguments
  QPoint(xpos: int, ypos: int): argument 1 has unexpected type 'float'
  QPoint(a0: QPoint): argument 1 has unexpected type 'float'
    __cause__ = None
    __class__ = <class 'TypeError'>
    __context__ = None
    __delattr__ = <method-wrapper '__delattr__' of TypeError object>
    __dict__ = {}
    __dir__ = <built-in method __dir__ of TypeError object>
    __doc__ = 'Inappropriate argument type.'
    __eq__ = <method-wrapper '__eq__' of TypeError object>
    __format__ = <built-in method __format__ of TypeError object>
    __ge__ = <method-wrapper '__ge__' of TypeError object>
    __getattribute__ = <method-wrapper '__getattribute__' of TypeError object>
    __gt__ = <method-wrapper '__gt__' of TypeError object>
    __hash__ = <method-wrapper '__hash__' of TypeError object>
    __init__ = <method-wrapper '__init__' of TypeError object>
    __init_subclass__ = <built-in method __init_subclass__ of type object>
    __le__ = <method-wrapper '__le__' of TypeError object>
    __lt__ = <method-wrapper '__lt__' of TypeError object>
    __ne__ = <method-wrapper '__ne__' of TypeError object>
    __new__ = <built-in method __new__ of type object>
    __reduce__ = <built-in method __reduce__ of TypeError object>
    __reduce_ex__ = <built-in method __reduce_ex__ of TypeError object>
    __repr__ = <method-wrapper '__repr__' of TypeError object>
    __setattr__ = <method-wrapper '__setattr__' of TypeError object>
    __setstate__ = <built-in method __setstate__ of TypeError object>
    __sizeof__ = <built-in method __sizeof__ of TypeError object>
    __str__ = <method-wrapper '__str__' of TypeError object>
    __subclasshook__ = <built-in method __subclasshook__ of type object>
    __suppress_context__ = False
    __traceback__ = <traceback object>
    args = ("arguments did not match any overloaded call:\n  Q...: QPoint): argument 1 has unexpected type 'float'",)
    with_traceback = <built-in method with_traceback of TypeError object>

The above is a description of an error in a Python program.  Here is
the original traceback:

Traceback (most recent call last):
  File "/home/Pacn/.var/app/org.kde.krita/data/krita/pykrita/imagine_board/imagine_board_modulo.py", line 3245, in paintEvent
    QPoint(w2 - (0.2*side), h2 - (0.2*side)),
TypeError: arguments did not match any overloaded call:
  QPoint(): too many arguments
  QPoint(xpos: int, ypos: int): argument 1 has unexpected type 'float'
  QPoint(a0: QPoint): argument 1 has unexpected type 'float'
```

After closing it the dock gets blank:

![image](https://user-images.githubusercontent.com/92924912/210924725-ac033434-0b88-4cc7-9a7b-00488b7ab8af.png)

Hovering the mouse over it makes the same python error appear.


EDIT: After having some images loaded changing the mode from preview to grid triggers the following: 
![image](https://user-images.githubusercontent.com/92924912/210927766-315b4e1b-b2c0-44df-958d-fa1b9be3e56d.png)
Log:
```
TypeError
Python 3.10.6: /usr/bin/python3
Thu Jan  5 23:03:42 2023

A problem occurred in a Python script.  Here is the sequence of
function calls leading up to the error, in the order they occurred.

 /home/Pacn/.var/app/org.kde.krita/data/krita/pykrita/imagine_board/imagine_board_modulo.py in paintEvent(self=<imagine_board.imagine_board_modulo.ImagineBoard_Grid object>, event=<PyQt5.QtGui.QPaintEvent object>)
 1558                         painter.drawRect(0,0,self.widget_width,self.widget_height)
 1559                     # Pixmap
 1560                     render = qpixmap.scaled(self.tn_x+1, self.tn_y+1, self.display_ratio, self.tn_smooth_scale)
 1561                     render_width = render.width()
 1562                     render_height = render.height()
render undefined
qpixmap = <PyQt5.QtGui.QPixmap object>
qpixmap.scaled = <built-in method scaled of QPixmap object>
self = <imagine_board.imagine_board_modulo.ImagineBoard_Grid object>
self.tn_x = 87.33333333333333
self.tn_y = 65.0
self.display_ratio = 1
self.tn_smooth_scale = 1
TypeError: arguments did not match any overloaded call:
  scaled(self, width: int, height: int, aspectRatioMode: Qt.AspectRatioMode = Qt.IgnoreAspectRatio, transformMode: Qt.TransformationMode = Qt.FastTransformation): argument 1 has unexpected type 'float'
  scaled(self, size: QSize, aspectRatioMode: Qt.AspectRatioMode = Qt.IgnoreAspectRatio, transformMode: Qt.TransformationMode = Qt.FastTransformation): argument 1 has unexpected type 'float'
    __cause__ = None
    __class__ = <class 'TypeError'>
    __context__ = None
    __delattr__ = <method-wrapper '__delattr__' of TypeError object>
    __dict__ = {}
    __dir__ = <built-in method __dir__ of TypeError object>
    __doc__ = 'Inappropriate argument type.'
    __eq__ = <method-wrapper '__eq__' of TypeError object>
    __format__ = <built-in method __format__ of TypeError object>
    __ge__ = <method-wrapper '__ge__' of TypeError object>
    __getattribute__ = <method-wrapper '__getattribute__' of TypeError object>
    __gt__ = <method-wrapper '__gt__' of TypeError object>
    __hash__ = <method-wrapper '__hash__' of TypeError object>
    __init__ = <method-wrapper '__init__' of TypeError object>
    __init_subclass__ = <built-in method __init_subclass__ of type object>
    __le__ = <method-wrapper '__le__' of TypeError object>
    __lt__ = <method-wrapper '__lt__' of TypeError object>
    __ne__ = <method-wrapper '__ne__' of TypeError object>
    __new__ = <built-in method __new__ of type object>
    __reduce__ = <built-in method __reduce__ of TypeError object>
    __reduce_ex__ = <built-in method __reduce_ex__ of TypeError object>
    __repr__ = <method-wrapper '__repr__' of TypeError object>
    __setattr__ = <method-wrapper '__setattr__' of TypeError object>
    __setstate__ = <built-in method __setstate__ of TypeError object>
    __sizeof__ = <built-in method __sizeof__ of TypeError object>
    __str__ = <method-wrapper '__str__' of TypeError object>
    __subclasshook__ = <built-in method __subclasshook__ of type object>
    __suppress_context__ = False
    __traceback__ = <traceback object>
    args = ("arguments did not match any overloaded call:\n  s...ormation): argument 1 has unexpected type 'float'",)
    with_traceback = <built-in method with_traceback of TypeError object>

The above is a description of an error in a Python program.  Here is
the original traceback:

Traceback (most recent call last):
  File "/home/Pacn/.var/app/org.kde.krita/data/krita/pykrita/imagine_board/imagine_board_modulo.py", line 1560, in paintEvent
    render = qpixmap.scaled(self.tn_x+1, self.tn_y+1, self.display_ratio, self.tn_smooth_scale)
TypeError: arguments did not match any overloaded call:
  scaled(self, width: int, height: int, aspectRatioMode: Qt.AspectRatioMode = Qt.IgnoreAspectRatio, transformMode: Qt.TransformationMode = Qt.FastTransformation): argument 1 has unexpected type 'float'
  scaled(self, size: QSize, aspectRatioMode: Qt.AspectRatioMode = Qt.IgnoreAspectRatio, transformMode: Qt.TransformationMode = Qt.FastTransformation): argument 1 has unexpected type 'float'
```

----------------------------------------------------------------------------------------------

Everything else seems to be working, still am gonna test it more and see if i can find more errors.

**Comment by EyeOdin** [comment]
these are not even bugs but just modules not working well on your end.

**Comment by starget24** [comment]
Oh thats my bad then i dig into it deeper and it seems the pyqt version that krita bundles has problems converting float arguments, the solution for this is to convert every float into int for QPoints and some other ones, after i did that every error dissapear and the plugins was working perfectly except for video playback, but thats another topic, can i suggest a merge request with the changes so you can evaluate them? Obviously if it doesnt't conflict with anything on your side, and considering this is actually my first time coding something for python i want to make sure i didn't do something stupid LMAO, i really want this to work on the krita flatpak for linux.

**Comment by EyeOdin** [comment]
I can do that but I would need to verify the merge very well before putting up on my side. usually I code alone so I am not used to verify code of others a light touch and it will create jittering or break entire functions. Some points changing the float is not possible and non negotiable to do and I dont expect other people to know that. I would evaluate case by case.

**Comment by EyeOdin** [comment]
@starget24 
Okay I reviewed all cases of this that you indicated. Check if it working now.
