### ISSUE TITLE
Bug: ZeroDivisionError when dragging image from browser

### ISSUE THREAD

**Issue by Konayachi** [EyeOdin/imagine_board#2]
I was dragging and dropping an image from the firefox browser directly to imagine board in reference mode.
I'm running Krita using the AppImage.

This is the error text:
```
ZeroDivisionError
Python 3.8.1: /usr/bin/python3
Wed Mar 15 20:04:00 2023

A problem occurred in a Python script.  Here is the sequence of
function calls leading up to the error, in the order they occurred.

 /path/to/imagine_board/imagine_board_modulo.py in paintEvent(self=<imagine_board.imagine_board_modulo.ImagineBoard_Reference object>, event=<PyQt5.QtGui.QPaintEvent object>)
 3474         if len(optimized) > 0:
 3475             # Optimized Square
 3476             box = Pixmap_Box(self, optimized)
 3477             min_x = box["min_x"]
 3478             min_y = box["min_y"]
box undefined
global Pixmap_Box = <function Pixmap_Box>
self = <imagine_board.imagine_board_modulo.ImagineBoard_Reference object>
optimized = [{'active': False, 'area': 0, 'bb': 271.0, 'bh': 0.0, 'bl': 278.0, 'br': 278.0, 'bt': 271.0, 'bw': 0.0, 'cb': 1.0, 'cl': 0.0, ...}]

 /path/to/imagine_board/imagine_board_modulo.py in Pixmap_Box(self=<imagine_board.imagine_board_modulo.ImagineBoard_Reference object>, lista=[{'active': False, 'area': 0, 'bb': 271.0, 'bh': 0.0, 'bl': 278.0, 'br': 278.0, 'bt': 271.0, 'bw': 0.0, 'cb': 1.0, 'cl': 0.0, ...}])
  207         perimeter = (2*delta_x) + (2*delta_y)
  208         area = delta_x * delta_y
  209         ratio = delta_x / delta_y
  210     # Return
  211     box = {
ratio undefined
delta_x = 0.0
delta_y = 0.0
ZeroDivisionError: float division by zero
    __cause__ = None
    __class__ = <class 'ZeroDivisionError'>
    __context__ = None
    __delattr__ = <method-wrapper '__delattr__' of ZeroDivisionError object>
    __dict__ = {}
    __dir__ = <built-in method __dir__ of ZeroDivisionError object>
    __doc__ = 'Second argument to a division or modulo operation was zero.'
    __eq__ = <method-wrapper '__eq__' of ZeroDivisionError object>
    __format__ = <built-in method __format__ of ZeroDivisionError object>
    __ge__ = <method-wrapper '__ge__' of ZeroDivisionError object>
    __getattribute__ = <method-wrapper '__getattribute__' of ZeroDivisionError object>
    __gt__ = <method-wrapper '__gt__' of ZeroDivisionError object>
    __hash__ = <method-wrapper '__hash__' of ZeroDivisionError object>
    __init__ = <method-wrapper '__init__' of ZeroDivisionError object>
    __init_subclass__ = <built-in method __init_subclass__ of type object>
    __le__ = <method-wrapper '__le__' of ZeroDivisionError object>
    __lt__ = <method-wrapper '__lt__' of ZeroDivisionError object>
    __ne__ = <method-wrapper '__ne__' of ZeroDivisionError object>
    __new__ = <built-in method __new__ of type object>
    __reduce__ = <built-in method __reduce__ of ZeroDivisionError object>
    __reduce_ex__ = <built-in method __reduce_ex__ of ZeroDivisionError object>
    __repr__ = <method-wrapper '__repr__' of ZeroDivisionError object>
    __setattr__ = <method-wrapper '__setattr__' of ZeroDivisionError object>
    __setstate__ = <built-in method __setstate__ of ZeroDivisionError object>
    __sizeof__ = <built-in method __sizeof__ of ZeroDivisionError object>
    __str__ = <method-wrapper '__str__' of ZeroDivisionError object>
    __subclasshook__ = <built-in method __subclasshook__ of type object>
    __suppress_context__ = False
    __traceback__ = <traceback object>
    args = ('float division by zero',)
    with_traceback = <built-in method with_traceback of ZeroDivisionError object>

The above is a description of an error in a Python program.  Here is
the original traceback:

Traceback (most recent call last):
  File "/path/to/imagine_board/imagine_board_modulo.py", line 3476, in paintEvent
    box = Pixmap_Box(self, optimized)
  File "/path/to/imagine_board/imagine_board_modulo.py", line 209, in Pixmap_Box
    ratio = delta_x / delta_y
ZeroDivisionError: float division by zero

```

**Comment by EyeOdin** [comment]
Updated. check if the error persists.
